services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env.compose
    environment:
      - PYTHONPATH=/code/src 
    ports:
      - "8002:8002"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - .:/code:rw
    depends_on:
      db_service:
        condition: service_healthy  # Ensures DB is ready before app starts
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml

  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=time-user
      - POSTGRES_PASSWORD=time-pw
      - POSTGRES_DB=timescaledb
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U time-user -d timescaledb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:
